### ISSUE TITLE
How did you make the cool circle that follows your mouse?

### ISSUE THREAD

**Issue by daribock** [HarjjotSinghh/Portfolio#2]
Hey Harjot, nice portfolio page! 

Can you please explain me how you made the cool circle that follows your mouse when browsing through your portfolio? :D

**Comment by HarjjotSinghh** [comment]
Hey @daribock, I am glad you liked the portfolio! Just so you know, this is not the repo for my current portfolio website, this is the repo for my old portfolio website. Well, regardless, here is how I implemented that circle which follows the mouse:

First, I added the required CSS:

```css
.cursor-inner {
  margin-left: -3px;
  margin-top: -3px;
  width: 6px;
  height: 6px;
  z-index: 100;
  opacity: 0.75;
  background-color: hsl(var(--primary));
  -webkit-transition: width 0.3s ease-in-out, height 0.3s ease-in-out,
    margin 0.3s ease-in-out, opacity 0.3s ease-in-out;
  transition: width 0.3s ease-in-out, height 0.3s ease-in-out,
    margin 0.3s ease-in-out, opacity 0.3s ease-in-out;
}
.cursor-inner.cursor-hover {
  margin-left: -40px;
  margin-top: -40px;
  width: 80px;
  height: 80px;
  background-color: hsl(var(--primary));
  opacity: 0.2;
}
.cursor-outer {
  margin-left: -15px;
  margin-top: -15px;
  width: 30px;
  height: 30px;
  border: 3px solid hsl(var(--primary));
  -webkit-box-sizing: border-box;
  box-sizing: border-box;
  z-index: 100;
  opacity: 0.5;
  -webkit-transition: all 0.11s ease-out;
  transition: all 0.11s ease-out;
}
.cursor-outer.cursor-hover {
  opacity: 0;
}
.mouse-cursor {
  position: fixed;
  left: 0;
  top: 0;
  pointer-events: none;
  border-radius: 50%;
  -webkit-transform: translateZ(0);
  transform: translateZ(0);
  visibility: hidden;
}
```
Then, I created a custom component called `Mouse` and saved it in a file called `Mouse.js`:
```jsx
"use client";
import { harjotUtils } from "@/utility";
import { Fragment, useEffect } from "react";
const Mouse = () => {
  useEffect(() => {
    harjotUtils.customCursor();
  }, []);

  return (
    <Fragment>
      <div className="mouse-cursor cursor-outer" />
      <div className="mouse-cursor cursor-inner" />
    </Fragment>
  );
};
export default Mouse;
```
Lastly, I added the required functionality in my custom utils called `harjotUtils`:
```js
export const harjotUtils = {
customCursor() {
    var myCursor = document.querySelectorAll(".mouse-cursor"),
      hamburger = document.querySelector(".hamburger"),
      kura_tm_topbar = document.querySelector(".kura_tm_topbar "),
      pointer = document.querySelector(".cursor-pointer"),
      e = document.querySelector(".cursor-inner"),
      t = document.querySelector(".cursor-outer");

    function mouseEvent(element) {
      element.addEventListener("mouseenter", function () {
        e.classList.add("cursor-hover"), t.classList.add("cursor-hover");
      });
      element.addEventListener("mouseleave", function () {
        e.classList.remove("cursor-hover"), t.classList.remove("cursor-hover");
      });
    }

    if (myCursor.length) {
      if (document.body) {
        let n,
          i = 0,
          o = !1;
        (window.onmousemove = function (s) {
          // console.log(document.querySelector(this));
          o ||
            (t.style.transform =
              "translate(" + s.clientX + "px, " + s.clientY + "px)"),
            (e.style.transform =
              "translate(" + s.clientX + "px, " + s.clientY + "px)"),
            (n = s.clientY),
            (i = s.clientX);
        }),
          document.body.addEventListener(
            "mouseenter",
            // "a,.kura_tm_topbar .trigger, .cursor-pointer",
            function () {
              let a = document.querySelectorAll("a");
              e.classList.add("cursor-inner"), t.classList.add("cursor-outer");

              for (let i = 0; i < a.length; i++) {
                const element = a[i];
                mouseEvent(element);
              }

              hamburger && mouseEvent(hamburger);
              kura_tm_topbar && mouseEvent(kura_tm_topbar);
              pointer && mouseEvent(pointer);
            }
          ),
          (e.style.visibility = "visible"),
          (t.style.visibility = "visible");
      }
    }
  }
}
```

And that was how I implemented that cool cursor follow effect! Let me know if you would like to know anything else, I will be more than happy to help!
